language: python
python:
  - "2.7"
  - "3.3"
install:
  # install funcsigs on python 2.7
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors funcsigs; fi
# command to run tests, e.g. python setup.py test
script:  "py.test test/"
